### ISSUE TITLE
Change icon to Corridor 

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/SlipsAndSpills#10]
Not sure about having a photo of a toilet as the icon for the app as there are a lot of negative connotations around toilets e.g. ‘money down the toilet’ (I’m sure you can think of others). I can live with it if you are busy but would prefer a nicer image like the long corridor.

**Comment by philiprbrenan** [comment]
Edit the file: 

https://github.com/philiprbrenan/SlipsAndSpills/blob/master/sourceFile.txt

by clicking on the pencil icon as shown in the screenshot
 
![changingtheicon](https://user-images.githubusercontent.com/7548378/28746322-c5032c9a-7481-11e7-8934-842c0b26b29a.png)

Then save the file and goto:

http://www.appaapps.com/cgi-bin/AppaAppsPhotoAppWww.pl?source=philiprbrenan%2FSlipsAndSpills

enter the app name:

http://www.appaapps.com/cgi-bin/AppaAppsPhotoAppWww.pl?source=philiprbrenan%2FSlipsAndSpills

push submit and wait about 20 seconds.

I have done this and the new app shpuld be available for download at:

http://www.appaapps.com/users/philiprbrenan/SlipsAndSpills/apk/slipsandspills.apk

**Comment by ghost** [comment]
Philip, I can see where to change the icon image spec in the text file. I am not clear on the next two steps because I can not open the links. This is for my future understanding, not now, as the icon photo is updated and I have the updated app on my phone.

Regards, Janet
