### ISSUE TITLE
Music overlaying audio

### ISSUE THREAD

**Issue by ghost** [philiprbrenan/SlipsAndSpills#20]
I understand this is the test bed app.
When the music plays you can't hear most of the audio prompts or feedbacks.

**Comment by philiprbrenan** [comment]
That is because you are in race mode and the app is making it difficult for you to make the test harder.  Once you make a mistake  the music will stop as you revert to normal play mode.

**Comment by ghost** [comment]
This doesn't make any sense and is not the right way to make the test harder. Making it harder needs to be based on the challenge of the test itself and not through the setting of external physical obstacles that are nothing to do with the content.

**Comment by ghost** [comment]
The music currently starts up for no apparent reason and all you can think about is that something has gone wrong and you need to work out how to shut it off. If the learner has answered a lot of questions correctly then why don't we give them a short tinkle of music and text or audio saying 'Well done. 10 questions answered correctly.' If this also launched them into a higher level of the game it would be a good full stop between levels so the learner would know what was happening. Forcing a learner to make a mistake to get rid of the music is really unfair.

**Comment by philiprbrenan** [comment]
Another way to turn off the music is to get through the race without making any mistakes - play then reverts to normal then to - but the user is unlikely to achieve this early on in the game.
