### ISSUE TITLE
Psychedelic words on screen

### ISSUE THREAD

**Issue by ghost** [philiprbrenan/SlipsAndSpills#21]
This is already under discussion between us. 
I find the flashing rainbow words really difficult to look at. They make me feel a bit dizzy and sick. I am worried about showing an app with the flashing words to anyone who is prone to migraine and epilepsy as flashing/strobing lights can trigger an attack.

**Comment by philiprbrenan** [comment]
I will be adding different themes that the user can select at will to allow  them to choose the most effective learning environment for them.

The nausea you are describing is quite normal - once you become used to it the experience  becomes rather pleasant and missed it if it is not there.

**Comment by ghost** [comment]
Ok different themes is a good idea. I'm still concerned about the flickering and its effect on health. We will need to explain what happens with this theme and put in a disclaimer. Can the words be colourful and have colour changes without all the flickering?

**Comment by philiprbrenan** [comment]
Develop a calmer theme by Thursday for meeting with Westminster council.

**Comment by philiprbrenan** [comment]
Added chess theme.

**Comment by philiprbrenan** [comment]
Moved to #40
