### ISSUE TITLE
Screen shots

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/SlipsAndSpills#24]
Please try taking a screen shot by swiping slowly left and then see if it turns up in the out/ folder of this repository?

**Comment by ghost** [comment]
I'm not sure Philip but I don't think that's working is it? I don't know where the out folder of the repository is though.

**Comment by philiprbrenan** [comment]
I can see that you are taking screen shots successfully!

 SlipsAndSpills/out/screenShot/1509818686273.jpg

**Comment by ghost** [comment]
Ok good.
