### ISSUE TITLE
Scale font of log to better fit large screens

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/SlipsAndSpills#30]
SUCCESS!

Scale font of log to better fit large screens

Created app: <b>https://github.com/philiprbrenan/SlipsAndSpills</b> successfully at the following links:

Download Android app: <b>http://www.appaapps.com/users/philiprbrenan/SlipsAndSpills/apk/SlipsAndSpills.apk</b>

See assets on web   : <b>http://www.appaapps.com/users/philiprbrenan/SlipsAndSpills/html/assets.html</b>

Play game on web    : <b>http://www.appaapps.com/users/philiprbrenan/SlipsAndSpills/html/playGame.html</b> (It's better on Android)

2017-11-04 at 19:10:59 v20171104-111  on:Pousadouros

**Comment by philiprbrenan** [comment]
I see!  You are probably holding your phone vertically and I am developing on a horizontal phone which would explain the difference.  I now scale from both the height and the width of the phone which I think will make the text on your phone a little smaller.

**Comment by ghost** [comment]
Ok thanks.
