### ISSUE TITLE
Falls isn’t clearly educationally

### ISSUE THREAD

**Issue by philiprbrenan** [philiprbrenan/SlipsAndSpills#36]
On the while I think that this is a good thing as we cannot force people to play these apps.  There  has to be a significant amount of play to keep the game fun and the student engaged  to allow the learning to occur "by stealth".

**Comment by ghost** [comment]
This is an interesting discussion in itself. Learners with 'cognitive competence' (intellectual ability) will probably cope with this 'schema' (feedback format). Learners with learning difficulties and less cognitive ability will not (and these learners are a large part of our core audience in Social Care - and among the audience groups of our partners).
This is going to be something we have to deal with. Do you want to have one version that works in the way it is now and another that works with more reinforcement of correct answers? It's working differently to the original Appa Apps SMP isn't it.

**Comment by philiprbrenan** [comment]
People  who have difficulty answering correctly will make mistakes, and thus will be presented with the confirmation response rather than with the new information response (most of the time). The app tracks all of this information and increases the reteach rate of existing material if the student is struggling.  Conversely, the app increases the rate of learning if  the student is progressing rapidly over known material and in danger of becoming bored.

It is this ability to track, and patiently reiterate as necessary that  makes this teaching method "better: in some ways than a human teacher. 

Conversely, the code uses the information gathered to locate and present the information the student does not know well and thus keep the more expert student engaged.

Such is the theory. We do need to confirm that this is actually happening.  One task I will be working on is writing the student's activity log into an email they can send to who ever they wish (so no privacy issues), if we can persuade them to send us some of these emails we will ab able to see if this is happening and helping in the real word.

**Comment by ghost** [comment]
I really like the idea that the learner can email someone to demonstrate that they are answering correctly! The volume and nature of correct answers would be good to show in the email. It will need to be explicit.

I still think we need to work on how we indicate that the learner is answering correctly/incorrectly. In Falls it’s impossible to have a clear idea about this currently.

What do you think about the ‘correct’ and ‘incorrect’ noises idea?

**Comment by philiprbrenan** [comment]
Moved to #35
